
package com.dxc.converter.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.dxc.converter.model.ObjectFactory;
import com.dxc.converter.model.PRMCALIREC;
import com.dxc.converter.model.PRMCALOREC;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PRMService", targetNamespace = "http://service.converter.prm111.dxc.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PRMService {

    /**
     * 
     * @param prmcalrq
     * @return
     *     returns com.dxc.converter.api.PRM.PRMCALOREC
     */
    @WebMethod(operationName = "PRMCAL", action = "PRMCALAction")
    @WebResult(name = "PRMCALO_REC", targetNamespace = "http://www.csc.smart/bo/schemas/PRMCALO", partName = "PRMCALRS")
    public PRMCALOREC convertPRM(
            @WebParam(name = "PRMCALI_REC", targetNamespace = "http://www.csc.smart/bo/schemas/PRMCALI", partName = "PRMCALRQ")
                    PRMCALIREC prmcalrq);
}
