spring:
  application:
    name: xml-json-convert-service
    
server:
  port: 8181
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-space-threads: 40
    max-connections: 20000
  connection-timeout: 5000
    
com:
  dxc:
    constant:
      VPM_FILE_NAME: INTLIFE.VPM
      CALLING_SYSTEM: Base
      CONTRACT_TYPE: DMY
      REGION: EAA
      LOCALE: CN
      LANGUAGE: E
      SOURCE_BUSINESS: 
      LOAD_PERCENT: 0
      REFUND_AGE: 999
      MORTALITY_CLASS: 0
    template:
      PRMCAL:
        premiumRiskAmount: /template/PRMCAL/premium_riskamount.json
        quotedCashvalue: /template/PRMCAL/quoted_cashvalue.json
    vpms_url: http://20.193.4.35:8080/vpms/v1/rest/exec